package abazdev.dicoding.abazapp.model;

import java.util.ArrayList;

import abazdev.dicoding.abazapp.R;

public class JajakhasData {
    public static String[][] data = new String[][]{
            {"Coto Makassar", "Heavy Meal", "Makanan khas Makassar ini memang memberikan kesan mendalam bagi siapa pun yang pernah menikmatinya. Hidangan ini kaya rempah, yang menjadikan rasanya ‘sangat renyah’ dan akan memberikan kesan mendalam kepada siapa pun pennikmatnya. Di Makassar, ada beberapa tempat yang direkomendasikan jika kamu tertarik mencoba kuliner ini. \n\nSalah satunya, Coto Nusantara dimana kuliner ini disajikan dengan kuah kental dan potongan daging besar, plus ekstra daun bawang dan bawang goreng yang disajikan terpisah. Lokasinya juga masih dekat dengan Pantai Losari, lho!", String.valueOf(R.drawable.coto)},
            {"Pallu Golla", "Dessert", "Pallu Golla artinya masakan gula, merujuk kepada masakan yang manis. Pallu Golla dianggap symbol kebahagiaan karena rasa manis yang berasal dari gula merah/gula aren dicampur santan kelapa kental. Dalam Bahasa Indonesia dikenal Kolak. Entah itu kolak pisang, ubi jalar atau labu, jika menggunakan gula merah dan santan maka disebut Pallu Golla. \n\nDalam tradisi Bugis-Makassar, hidangan ini adalah wajib dalam acara memulai sesuatu, seperti menempati rumah baru, atau menu pertama Ramadhan. Konon karena rasanya yang manis, diharapkan semuanya akan berakhir manis juga.", String.valueOf(R.drawable.pallugolla)},
            {"Barongko", "Dessert", "Barongko rasanya manis, dan lembut, dapat disajikan dalam keadaan dingin. Rasa manis akan mengembalikan stamina setelah seharian berpuasa menahan lapar dan dahaga, sedangkan tekstur barongko yang lembut memungkinkan lambung yang seharian kosong jadi lebih mudah untuk mencernanya. \n\nSaat lebaran pun, Barongko selalu terhidang sebagai makanan pembuka ataupun penutup untuk keluarga dab tamu yang datang bersilaturahmi.", String.valueOf(R.drawable.barongko)},
            {"Cucur Bayao", "Dessert", "Si kue Manis simbol harapan Pengantin. Cucur Bayao ini punya rasa manis dan selalu disajikan dalam pesta pernikahan. \n\nDalam sebuah bosara' atau baki berkaki tinggi berisikan kue, cucuru bayao disajikan bersama barongko,sikaporo, taloba, dsb. \n\nDalam bahasa Makassar 'Cucuru' berarti kue sedangkan 'bayao' artinya telur. Memang, kue ini berbahan dasar telur, gula pasir, dan kenari. Bentuknya bulat pipih dan berwarna kuning tua. Teksturnya lembut dengan rasa manis juga gurih khas aroma telur. Cita rasa manis yang kental pada kue-kue yang disajikan di pesta pernikahan Bugis Makassar merupakan simbol harapan akan manisnya kehidupan yang akan diarungi kedua mempelai. Mitos lain, anak gadis yang mencicipi kue tradisional ini di upacara pernikahan dipercaya jodohnya aka segera tiba.", String.valueOf(R.drawable.cucurubayao)},
            {"Bannang-Bannang", "Snack", "Bannang-bannang merupakan salah satu makanan khas dari Sulawesi Selatan. Dalam bahasa Makassar disebut bannang-bannang, sedangkan dalam bahasa Bugis disebut nennu’-nennu’. Kue yang berbahan dasar dari tepung beras dan gula merah ini memiliki bentuk seperti benang kusut. Bannang-bannang sendiri merupakan salah satu kue yang selalu ada dalam lamaran hingga pernikahan. \n\nBannang-bannang memiliki bentuk seperti benang kusut, yaitu benang yang pangkal dan ujungnya tidak tahu berada dimana. Hal ini menggambarkan beberapa makna dan filosofi, yaitu pertama sebagai manusia kita tidak perlu mempermasalahkan siapa kita, darimana asal usul kita, asalkan selama yang kita lakukan adalah mulia, maka lakukanlah. Makna kedua, yaitu sebagai penggambaran kehidupan rumah tangga / pernikahan sebagai satu kesatuan yang saling terkait (bergabungnya 2 keluarga yang saling membutuhkan dan bekerja sama) dan takkan pernah bisa dipisahkan hingga maut memisahkan. Semakin kusut maka makin sulit untuk diurai atau dipisahkan. Sedangkan rasa gurih dan manis yang dihasilkan dari bannang-bannang menggambarkan sebuah harapan manisnya perjalanan dari pernikahan hingga proses berumah tangga.", String.valueOf(R.drawable.bannang2)},
            {"Buroncong", "Snack", "Kue Buroncong biasa juga disebut beroncong, garoncong, geroncong, atau kue ganco kalo di daerah lain mirip-mirip kue pancong atau kue pukis. Dengan menggunakan gerobak yang di desain khusus para pedagang Buroncong siap berkeliling menjajakan panganan khas ini. \n\nGerobak Buroncong dilengkapi dengan tungku pembakaran yang di atasnya terdapat cetakan baroncong, kotak kaca pajangan, wadah penyimpan adonan kental bahan baroncong, dua buah ganco dan sendok besar pengaduk adonan, serta ruang penyimpanan kayu bakar dan kelengkapan lainnya. Beberapa gerobak buroncong dilengkapi pula dengan pedal pengayuh seperti sebuah becak, berikut sadel dudukan Sang Pengayuh terkadang juga di panggul sambil berkeliling kampung atau nongkrong di pasar dan pusat keramaian. \n\nBuroncong merupakan salah satu penganan khas kota makassar. Kue ini biasanya dihidangkan dipagi hari dalam kondisi hangat bersama teh manis atau kopi. Kalau tidak sempat buat sendiri penganan ini, bisa juga didapatkan dengan mudah di sekitaran penjual-penjual kue atau penjual khusus buroncong yang dijajakan tiap pagi menggunakan gerobak.", String.valueOf(R.drawable.buroncong)},
            {"Konro", "Heavy Meal", "Konro atau 'Sop Konro' termasuk masakan berkuah, namun kuahnya berwarna cokelat kehitaman dan berbahan dasar iga atau tulang rusuk sapi yang bercita rasa gurih. Kunci dari gurihnya sop ini adalah bumbu yang terbuat dari kacang tanah. Selain gurih, sop ini juga terasa hangat di mulutnkarena terbuat dari rempah-rempah seperti merica, cengkeh, pala, dan lainnya. \n\nDibandingkan dengan Coto Makassar yang belum diketahui asal-usulnya, Sop Konro dapat dirunut latar belakang sejarahnya. Makanan tradisional asal Sulawesi Selatan ini mulai dikenal sejak tahun 1960-an yang dipopulerkan oleh Pak Hanafing, lelaki yang berprofesi sebagai guru. Ia memulai usaha Sup Konro sekitar tahun 1962 di bawah sebuah tenda biru di dekat Lapangan Karebosi, Kota Makassar. \n\nSeiring dengan berjalannya waktu, kini Sop Konro tidak hanya disajikan dalam bentuk kuah saja, tapi juga tidak berkuah. Sop Konro yang tidak berkuah terdiri dari dua macam, yaitu Sop Konro Bakar dan Sop Konro Rica-Rica. Meskipun cara menyajikan berbeda, namun semuanya tetap menggunakan bumbu dan rempah-rempah yang sama. Komponen bumbu dan rempah-rempah tersebut di antaranya adalah kacang merah, bawang putih, cengkeh, cabai, kayu manis, biji pala, kunyit, ketumbar, merica, dan kluwak. Setiap komponen memiliki cita rasa, warna, dan aroma yang berbeda sehingga perpaduannya melahirkan cita rasa baru yang mampu menggugah selera. Oleh karena itu, masakan khas Bugis-Makassar ini mendapat predikat Juara Nasional dalam ajang Usaha Kecil dan Menengah (UKM) Pangan Award 2011, dengan kategori Cita Rasa Terbaik.", String.valueOf(R.drawable.konro)},
            {"Pallumara", "Side Dishes", "Lebih tertarik untuk menikmati seafood di Makassar, kamu bisa mencoba Palumara, makanan berbahan dasar ikan. Sup berkuah kuning dari bumbu kunyit ini mirip dengan ikan asam manis. Kepala kakap merah menjadi bahan dasarnya, dengan tongkol atau bandeng menjadi pengganti. \n\nCara terbaik menikmati Palumara adalah dengan nasi hangat, ditemani dengan minumaan dingin. Spot yang paling tepat untuk mendapatkan kesan paling pas adalah di rumah makan Ulu Juku, yang tidak hanya menyajikan Palumara, tapi juga makanan khas Makassar lainnya.", String.valueOf(R.drawable.pallumara)},
            {"Baruasa", "Snack", "Salah satu kue tradisional yang hampir jarang kita temui adalah kue Baruasa. Kue Baruasa' adalah kuliner yang hanya disajikan saat lebaran hingga panen padi. Kue ini juga wajib ada jika ada acara pernikahan atau perayaan Idul Fitri, tidak hanya itu kue ini juga disajikan juga ketika ada hajatan seperti lomba domino ketika malam Mapaccing, dan hajatan-hajatan lainnya. \n\n", String.valueOf(R.drawable.baruasa)},
            {"Se'ro", "Snack", "Se’ro yang berarti gayung adalah sebutan bagi penganan berbahan dasar beras ketan yang dibalur gula. Sekilas, jika melihat bentuknya, tak ada kemiripan kue ini dengan gayung air yang umum digunakan di rumah. Namun, menurut penuturan pembuatnya Daeng Inga, dahulu bentuk gayung yang digunakan oleh masyarakat kerajaan Gowa berbentuk persis penganan manis ini.\n\nKue tradisional ini terdiri atas empat bahan, yakni tepung beras, telur, gula, dan minyak goreng. Tepung beras dicampur bersama telur sesuai takaran yang ditentukan. Setelah adonan kalis persiapan selanjutnya adalah membentuk adonan. Daeng Inga menuturkan bagian membentuk penganan ini adalah bagian yang cukup sulit. “Karena dibuat tanpa menggunakan cetakan, bentuk-bentuknya dibuat menggunakan tangan” kata Daeng Inga. Bentuk gulungan yang bergelombang pada kue Se’ro-se’ro dibentuk menggunakan ibu jari. Proses ini pula yang menentukan ketebalan dari kue Se’ro-se’ro. \n\nBentuk yang menyerupai gayung pada kue Se’ro-se’ro dipercaya sebagai penambah rezeki bagi  pasangan pengantin. Selain pada hajatan pernikahan kue ini juga biasa ditemukan pada hajatan penamatan Alquran, akikah, atau pun Mappasili’ atau memandikan ibu hamil. Satu hal yang menjadi keistimewaan kue ini nama kampung yang menjadi sentra produksi bernama sama dengan penganan khas masyarakat Gowa ini, yakni kampung Se’ro.", String.valueOf(R.drawable.sero)},
            {"Dange", "Snack", "Sepintas kue ini mirip dengan kue pukis atau sagu rangi. Rasanya gurih, manis dan legit karena ada campuran kelapa parut dan juga gula merahnya. Sayangnya, kue legit enak ini sudah jarang sekali dijumpai. \n\nJika Anda pernah berkunjung ke kota Makasar, mungkin kue tradisional ini pernah Anda cicipi. Kue Dange pulubollong ini merupakan salah satu jajanan tradisional khas masyarakat Bugis. Penjualnya banyak sekali dijumpai di ruas-ruas jalan di sepanjang bandara, tidak hanya disitu saja anda dapat menemukan sepanjang jalan poros kab.Pangkep. \n\nKue Dange berbahan dasar tepung ketan hitam, parutan kelapa, gula merah, dan juga garam. Tepung ketan hitam, parutan kelapa dan juga garam dicampur hingga menjadi sebuah adonan. Adonan yang sudah dicampuir ini kemudian dikukus agar kue tahan lama sebelum akhirnya dimasukkan ke dalam cetakan dari tanah liat yang menyerupai cetakan kue pukis. \n\nSaat dibakar, bagian tengah kue dange ini dibuat ceruk untuk diisi gula merah yang sudah digerus halus. Adonan yang sudah diisi kemudian dibakar hingga matang. Rasanya gurih-gurih manis karena campuran gula merah dan juga kelapa parut yang dicampurkan ke dalam adonan. Hmm.. sepintas mirip seperti sagu rangi juga! \n\nKue Dange Pulubollong ini terbilang cukup langka, dulu banyak dijumpai di sekitar Pangkajene. Tapi kini penjual kua dange ini sudah jarang sekali. Hmm.. jika Anda berkesempatan mampir ke kota Makasar, kue ini bisa jadi tujuan wisata kuliner Anda di sana jika beruntung menemukannya.", String.valueOf(R.drawable.dange)},
            {"Sara'ba", "Drinks", "Makassar selain terkenal dengan minuman sari buah markisa yang sudah beredar ke manca negara, ada juga minuman lain yang menghangatkan lagi mengembalikan stamina yang loyo yakni sarabba. \n\nSarabba adalah minuman khas Makassar yang terbuat dari campuran jahe, kuning telur, gula aren, santan dan merica bubuk. Sarabba cocok untuk mengusir flu, menghangatkan badan, mengeluarkan angin dari tubuh saat masuk angin, paling asik sebagai teman disaat begadang nonton bola, syukur-syukur bangun malam buat solat tahajud. \n\nMasyarakat Makassar sebagian besar mengkonsumsinya sebagai pemulih stamina karena kuning telur dipercaya sebagai pemulih stamina (jamu), penawar letih setelah seharian beraktivitas dan untuk menghangatkan badan. Kini, tangan-tangan kreatif telah mengajak kita memudahkan untuk menikmati minuman khas Makassar ini di luar kota Makassar yakni dengan menyajikannya dalam sebuah kemasan. Sarabba bubuk instant maupun berupa minuman sarabba botolan ditawarkan kepada masyarakat yang belum berkesempatan berkunjung ke Makassar.", String.valueOf(R.drawable.sarabbaa)},
            {"Sirup DHT", "Drinks", "Sirup DHT bukan sirup biasa pada umumnya. Oleh-oleh Khas Makassar ini menjadi andalan Kota Makassar yang dibuat dengan rasa pisang ambon. Rasanya sih mirip sirup tjampolay khasnya Cirebon, namun ada sedikit perbedaan yang memberikan kekhasan dari Sirup DHT ini. Perlu Kamu tahu bahwa produk dari sirup ini tidak pernah berubah kemasannya sejak zaman dulu.", String.valueOf(R.drawable.dht)}
    };


    public static ArrayList<Jajakhas> getListData(){
        ArrayList<Jajakhas> list = new ArrayList<>();
        for (String[] aData : data) {
            Jajakhas jajakhas = new Jajakhas();
            jajakhas.setName(aData[0]);
            jajakhas.setCategory(aData[1]);
            jajakhas.setDescription(aData[2]);
            jajakhas.setPhoto(aData[3]);
            list.add(jajakhas);
        }
        return list;
    }
}
